# Generated by Django 4.2.3 on 2023-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resshaumains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ressourcesdelegation', models.IntegerField(max_length=5)),
                ('ressourcessocial', models.IntegerField(max_length=5)),
            ],
        ),
    ]
