# Generated by Django 4.2.3 on 2023-08-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('valeur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire', models.CharField(max_length=100)),
                ('valeur', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='resshaumains',
            name='ressourcesdelegation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resshaumains',
            name='ressourcessocial',
            field=models.IntegerField(),
        ),
    ]
