# Generated by Django 4.2.3 on 2023-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_depenses_valeur_alter_revenus_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creancier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
