# Generated by Django 4.2.3 on 2023-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialyseDataYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('nbrPatients', models.IntegerField()),
                ('nbrSessions', models.IntegerField()),
                ('nbrMachines', models.IntegerField()),
                ('nbrPatientsUneMachine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nbrSessionsUneMachine', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
