# Generated by Django 4.2.3 on 2023-09-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dialysedatayear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DialyseDataYear',
        ),
    ]
