# Generated by Django 4.2.3 on 2023-09-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_dialysedatayear'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialyseDataYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datas', models.CharField(max_length=30)),
                ('y2012', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2013', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2014', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2015', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2016', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2017', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2018', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2019', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2020', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y2021', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
