# Generated by Django 4.2.3 on 2023-09-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_dialysedatayear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2012',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2013',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2014',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2015',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2016',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2017',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2018',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2019',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2020',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2021',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
