# Generated by Django 4.2.3 on 2023-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_dialysedatayear_y2012_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2012',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2013',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2014',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2015',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2016',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2017',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2018',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2019',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2020',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='y2021',
            field=models.IntegerField(),
        ),
    ]
