# Generated by Django 4.2.3 on 2023-09-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_dialysedatayear_y2012_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialysedatayear',
            old_name='y2012',
            new_name='nbrMachines',
        ),
        migrations.RenameField(
            model_name='dialysedatayear',
            old_name='y2013',
            new_name='nbrPatients',
        ),
        migrations.RenameField(
            model_name='dialysedatayear',
            old_name='y2014',
            new_name='nbrSessions',
        ),
        migrations.RenameField(
            model_name='dialysedatayear',
            old_name='y2015',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='datas',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2016',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2017',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2018',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2019',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2020',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='y2021',
        ),
    ]
