# Generated by Django 4.2.3 on 2023-09-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_y2012_dialysedatayear_nbrmachines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialysedatayear',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
