# Generated by Django 4.2.3 on 2023-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_dialysedatayear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutDePatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=50)),
                ('y2018', models.IntegerField()),
                ('y2019', models.IntegerField()),
                ('y2020', models.IntegerField()),
                ('y2021', models.IntegerField()),
            ],
        ),
    ]
