# Generated by Django 4.2.3 on 2023-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('concept', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
