# Generated by Django 4.2.3 on 2023-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_activitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
