# Generated by Django 4.2.3 on 2023-09-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_service_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
