# Generated by Django 4.2.3 on 2023-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_description_activitie_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
