# Generated by Django 4.2.3 on 2023-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_service_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coutdepatients',
            name='column',
        ),
        migrations.RemoveField(
            model_name='coutdepatients',
            name='id',
        ),
        migrations.RemoveField(
            model_name='depenses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dettes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dialysedatayear',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resshaumains',
            name='id',
        ),
        migrations.RemoveField(
            model_name='revenus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coutdepatients',
            name='informaton',
            field=models.CharField(default=2, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitie',
            name='titre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='type',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dettes',
            name='creancier',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dialysedatayear',
            name='year',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resshaumains',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='partenaire',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='titre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
