# Generated by Django 4.2.3 on 2023-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_coutdepatients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='email',
        ),
    ]
