# Generated by Django 4.2.3 on 2023-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitie',
            name='titre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
